#!/usr/bin/env python3
"""Build combined metadata for the AB-OED demo.

Outputs a single JSON file used by the web demo:
  plots/ab_oed_meta.json

Schema (keyed by labels_used as string):
  {
    "10": {"next_ad": "A", "x_star": {"x1": 1.23, "x2": -0.45}},
    ...
  }

Inputs:
- plots/ab_oed_next_ad.json (already extracted earlier)
- plots/ab_oed_star.json (generated by scripts/extract_oed_star_metadata.py)

Usage:
  python3 scripts/build_ab_oed_meta.py
"""

from __future__ import annotations

import json
from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    plots = root / "plots"

    next_ad_path = plots / "ab_oed_next_ad.json"
    star_path = plots / "ab_oed_star.json"
    out_path = plots / "ab_oed_meta.json"

    if not next_ad_path.exists():
        raise SystemExit(f"Missing {next_ad_path}")
    if not star_path.exists():
        raise SystemExit(f"Missing {star_path} (run extract_oed_star_metadata.py)")

    next_ad = json.loads(next_ad_path.read_text(encoding="utf-8"))
    star = json.loads(star_path.read_text(encoding="utf-8"))

    merged: dict[str, dict] = {}
    keys = sorted(set(next_ad.keys()) | set(star.keys()), key=lambda s: int(s))
    for k in keys:
        entry: dict[str, object] = {}
        if k in next_ad:
            entry["next_ad"] = next_ad[k]
        if k in star:
            entry["x_star"] = star[k]
        merged[k] = entry

    out_path.write_text(json.dumps(merged, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} with {len(merged)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
